extraEnv:
  - name: MB_SITE_URL
    value: https://kids-metabase.baptist.com.au

database:
  type: "postgres"
  existingSecret: database-creds
  existingSecretConnectionURIKey: connectionUri
  persistence:
    enabled: true

image:
  repository: docker.io/metabase/metabase