apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: '8.6.0'
      helm:
        valueFiles:
          - $values/apps/argo-cd/values.yaml
    - repoURL: https://github.com/Asherslab/gsbc.argo
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true