apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.19.0
      helm:
        valueFiles:
          - "$values/apps/cert-manager/values.yaml"
    - repoURL: https://github.com/Asherslab/gsbc.argo
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Asherslab/gsbc.argo
      path: apps/cert-manager/app
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true