apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argo-cd
spec:
  project: default
  destination:
    namespace: longhorn
    server: https://kubernetes.default.svc
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.10.1
      helm:
        valueFiles:
          - "$values/apps/longhorn/values.yaml"
    - repoURL: https://github.com/Asherslab/gsbc.argo
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Asherslab/gsbc.argo
      path: apps/longhorn/app
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true