init:
  loadExamples: true

bootstrapScript: |
  #!/bin/bash
  
  # Install system-level dependencies
  apt-get update && apt-get install -y \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config

  # Install required Python packages
  uv pip install \
    authlib \
    psycopg2-binary \
    mysqlclient \

  # Create bootstrap file if it doesn't exist
  if [ ! -f ~/bootstrap ]; then
    echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap
  fi

extraEnvRaw:
  - name: SUPERSET_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: secret-key
        key: SUPERSET_SECRET_KEY

postgresql:
  auth:
    existingSecret: postgres-credentials
  image:
    repository: bitnamilegacy/postgresql
    tag: "14.17.0-debian-12-r3"

redis:
  image:
    repository: bitnamilegacy/redis