init:
  loadExamples: true

extraEnvRaw:
  - name: SUPERSET_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: secret_key
        key: secret_key

postgresql:
  auth:
    existingSecret: postgres-credentials
  image:
    repository: bitnamilegacy/postgresql
    tag: "14.17.0-debian-12-r3"

redis:
  image:
    repository: bitnamilegacy/redis