init:
  loadExamples: true

postgresql:
  auth:
    existingSecret: postgres-credentials
  image:
    repository: bitnamilegacy/postgresql
    tag: "14.17.0-debian-12-r3"

redis:
  image:
    repository: bitnamilegacy/redis